flask_app/__init__.py
from flask import Flask
from .routes.home import home_bp
from .routes.about import about_bp
from .routes.litters import litters_bp
from .routes.contact import contact_bp
import os

def create_app():
    app = Flask(__name__, template_folder=os.path.join(os.path.dirname(__file__), 'templates'))

    #incarca blueprints
    app.register_blueprint(home_bp)
    app.register_blueprint(about_bp)
    app.register_blueprint(litters_bp)
    app.register_blueprint(contact_bp)

    return app

flask_app/routes/about.py
from flask import Blueprint, render_template

about_bp = Blueprint('about', __name__)

@about_bp.route('/despre')
def about():
    return render_template('about.html', page_name = "Despre Nobu's Friends")

flask_app/routes/contact.py
from flask import Blueprint, render_template, request, redirect, url_for

contact_bp = Blueprint('contact', __name__)

@contact_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        return redirect(url_for('contact.thank_you'))
    return render_template('contact.html', page_name="Contacteaza-ne")

@contact_bp.route('/thank-you')
def thank_you():
    return render_template('thank_you.html', page_name="Multumim!")

flask_app/routes/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def home():
    return render_template('home.html', page_name = "Bun venit la Nobu's Friends!")

flask_app/routes/litters.py
from flask import Blueprint, render_template

litters_bp = Blueprint('litters', __name__)

@litters_bp.route('/cuiburi')
def litters():
    return render_template('litters.html', page_name = "Cuiburi")

flask_app/templates/about.html
{% extends 'base.html' %}


{% block content %}

<section id="about-us">
    <div class="container">

        <section id="who-we-are">
            <h2>Cine suntem noi?</h2>
            <div class="who-we-are-content">
                <div class="who-we-are-image-container">
                    <img class="who-we-are-img" 
                         src="{{ url_for('static', filename='images/poza-concurs-sofisticat-bogdan-alexandra.jpg') }}" 
                         alt="Nobu's Friends at Sofisticat">
                    <img class="who-we-are-img" 
                         src="{{ url_for('static', filename='images/poza-concurs-alexandra-margot.jpg') }}" 
                         alt="Alexandra si Margot">
                </div>
        
                <div class="who-we-are-text">
                    <p>Suntem <strong>Nobu's Friends Cattery</strong>, o crescătorie dedicată creșterii și selecției pisicilor <strong>Maine Coon</strong>, situată în comuna Nicolae Bălcescu, județul Bacău. La noi, fiecare pisică este crescută cu multă grijă, dragoste și respect, pentru a deveni un companion de încredere și deosebit pentru viitorii săi stăpâni. Ne concentrăm pe furnizarea de pisici <strong>Maine Coon</strong> sănătoase, cu pedigree de calitate, care să aducă bucurie și armonie în casele celor care le adoptă.</p>
                    <p>Scopul nostru este să oferim nu doar o pisică, ci un prieten loial și iubitor, care să fie alături de familie pe termen lung. Prin intermediul site-ului nostru, dorim să facem cunoscută calitatea și profesionalismul serviciilor noastre, oferind un canal de comunicare transparent și direct pentru toți cei interesați să înființeze o relație de încredere cu <strong>Nobu's Friends Cattery</strong>.</p>
                </div>
                <div class="who-we-are-image-container">
                    <img class="who-we-are-img" 
                         src="{{ url_for('static', filename='images/poza-concurs-sofisticat-alexandra-carucior.jpg') }}" 
                         alt="Alexandra si Armageddon">
                    <img class="who-we-are-img" 
                         src="{{ url_for('static', filename='images/poza-safari-nobu.jpg') }}" 
                         alt="Nobu si prietenii">
                </div>
            </div>
        </section>

        <section id="our-values">
            <h2>Care sunt valorile noastre?</h2>
            <ul>
                <li><strong>Calitate și sănătate:</strong> Fiecare pisică <strong>Maine Coon</strong> din crescătoria noastră beneficiază de îngrijire veterinară de calitate și o alimentație sănătoasă, pentru a fi pregătită să își găsească un stăpân iubitor. Ne asigurăm că toate animalele noastre sunt în perfectă stare de sănătate și că provin din părinți cu pedigree verificate.</li>
                <li><strong>Profesionalism:</strong> Echipa noastră este formată din experți în creșterea și îngrijirea pisicilor <strong>Maine Coon</strong>, iar procesul nostru de selecție este riguros și responsabil. Fiecare pisică este crescută într-un mediu curat, sigur și prietenos.</li>
                <li><strong>Relație pe termen lung:</strong> Ne dorim ca toți clienții noștri să găsească la <strong>Nobu's Friends Cattery</strong> nu doar o pisică, ci un companion de încredere. Suntem mereu disponibili pentru orice întrebări sau recomandări, chiar și după ce pisica ajunge în noul său cămin.</li>
                <li><strong>Transparență și încredere:</strong> Fiecare client poate conta pe noi pentru un serviciu transparent și de calitate. Răspundem prompt la întrebările clienților și oferim toate informațiile necesare despre istoricul și starea de sănătate a fiecărei pisici. Suntem deschiși și sinceri în fiecare etapă a procesului de vânzare.</li>
            </ul>
        </section>
    </div>
</section>

<section id="about-us-cta">
    <div class="about-us-cta-container">
        <h2>Ești gata să primești în casa ta un Maine Coon?</h2>
        <p>Acum că ai aflat mai multe despre noi și despre angajamentul nostru față de pisicile Maine Coon sănătoase și fericite, ne-ar plăcea să te ajutăm să îți găsești noul prieten felin. Fie că vrei mai multe informații despre procesul nostru de creștere, pisicile disponibile sau pur și simplu vrei să discutăm despre această rasă minunată, suntem aici să te ajutăm în fiecare pas al călătoriei tale!</p>
        <a href="/contact" class="about-us-cta-button">Contactează-ne pentru mai multe informații</a>
    </div>
</section>
{% endblock %}

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='index.css') }}">
    <meta charset="UTF-8">
    <meta name="description" content="Nobu's Friends Cattery">
    <meta name="keywords" content="cattery, maine, mainecoon, maine coon">
    <meta name="author" content="Paul Jeleanu">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Nobu's Friends Cattery - {{ page_name }} </title>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icon-modified.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Averia+Libre:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Host+Grotesk:ital,wght@0,800;1,800&family=Sour+Gummy:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body class="{% block body_class %}about-us-page{% endblock %}">
    <header>
        <div class="header-container">
            <div class="icon-image-homepage">
                <a href="/"><img class="icon" src="/static/images/{{'icon.jpg'}}" alt="Logo"></a>
            </div>
            <div class="navigation-menu">
                    <ul class="navbar-buttons-list">
                        <li><a href="/"> Acasa </a></li>
                        <li><a href="/despre"> Despre Noi </a></li>
                        <li><a href="/cuiburi"> Cuiburi </a></li>
                        <li><a href="/contact"> Contact </a></li>
                    </ul>
            </div>
        </div>
    </header>

    <main>
        <div class="page-title-container">
            <div class="page-title-section">
                <h1 id="page-name">{{ page_name }}</h1>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </main>

    <div class="footer">
        <p class="footer-paragraph"> Copyright &copy; 2025 NOBU'S FRIENDS CATTERY  |  All Rights Reserved </p>
    </div>

</body>

</html>

flask_app/templates/contact.html
{% extends 'base.html' %}


{% block content %}


<!-- formular de contact: nume, prenume, numar de telefon, email, oras, mesaj (optional) max 255 char-->>

<section id="contact-section">
    <div class="contact-container">
        <div class="contact-form-container">
            <h2>Contactează-ne</h2>
            <form action="{{ url_for('contact.contact') }}" method="POST">
                <div class="form-group">
                    <label for="name">Nume</label>
                    <input type="text" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Mesaj</label>
                    <textarea id="message" name="message" rows="4" required></textarea>
                </div>
                <button type="submit" class="cta-button">Trimite</button>
            </form>
        </div>

        <div class="contact-info-container">
            <h2>Informații Contact</h2>
            <ul>
                <li><strong>Adresă:</strong> Strada Principală, Nr. 123, comuna Nicolae Bălcescu, Bacău, România</li>
                <li><strong>Telefon:</strong> +40 731393614</li>
                <li><strong>Email:</strong> info@nobusfriends.com</li>
                <li><strong>Program:</strong> Luni - Vineri: 9:00 AM - 6:00 PM</li>
            </ul>
        </div>
    </div>
</section>
{% endblock %}

flask_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
<section class="home-section breeding-philosophy">
    <div class="section-content">
        <h2>Filosofia noastră de breeding</h2>
        <div class="section-content-wrapper">
            <p>Ne concentrăm pe creșterea de pisici Maine Coon sănătoase și fericite, cu temperament excepțional. Scopul nostru este să ne asigurăm că fiecare pisoi este bine socializat și pregătit pentru o viață fericită alături de noua sa familie.</p>
        </div>
    </div>
</section>

<section class="home-section reliability">
    <div class="section-content">
        <h2>Fiabilitate în relațiile cu clienți</h2>
        <div class="section-content-wrapper">
            <p>Suntem dedicați să oferim servicii excelente clienților noștri. De la momentul în care întrebați despre un pisoi până în ziua în care noul vostru prieten felin ajunge acasă, garantăm un proces clar și fără probleme.</p>
        </div>
    </div>
</section>

<section class="home-section legal-pedigree">
    <div class="section-content">
        <h2>100% Pedigree</h2>
        <div class="section-content-wrapper">
            <p>Toate pisicile noastre sunt complet înregistrate la asociațiile de rase recunoscute. Ne asigurăm că practicile noastre de reproducție sunt etice.</p>
        </div>
    </div>
</section>
</main>


<section class="home-section call-to-action">
    <h2>Intră în contact cu noi pentru mai multe informații!</h2>
    <a href="/contact" class="cta-button">Contactează-ne</a>
    <a href="/cuiburi" class="cta-button">Vezi cuiburile disponibile</a>
</section>

<!-- Galerie cu pisiki, galerie de la concurs -->

<section class="home-section gallery">
    <h2>Pisicii noștri fericiți</h2>
    <div class="gallery-grid">
        <img src="{{ url_for('static', filename='images/483982123_675742091870831_2153764201709045633_n.jpg') }}" type="image/jpg" alt="Maine Coon 1">
        <img src="{{ url_for('static', filename='images/daphne.jpg' ) }}" type="image/jpg" alt="Maine Coon 2">
        <img src="{{ url_for('static', filename='images/486823438_686192354159138_2468757181954243557_n.jpg' ) }}" type="image/jpg" alt="Maine Coon 3">
        <img src="{{ url_for('static', filename='images/dusty.jpg' ) }}" type="image/jpg" alt="Maine Coon 4">
        <img src="{{ url_for('static', filename='images/483653293_674089942036046_27617814628554744_n.jpg'   ) }}" type="image/jpg" alt="Maine Coon 5">
        <img src="{{ url_for('static', filename='images/ekko.jpg' ) }}" type="image/jpg" alt="Maine Coon 6">
    </div>
</section>




<section class="home-section social-media">
    <h2>Urmărește-ne pe rețelele sociale!</h2>
    <div class="social-media-buttons-container">
        <button class="social-media-button">
            <a href="https://www.facebook.com/yourpage" target="_blank">
                <i class="fab fa-facebook-f" style="font-size: 50px;"></i> 
            </a>
        </button>

        <button class="social-media-button">
            <a href="https://www.instagram.com/yourprofile" target="_blank">
                <i class="fab fa-instagram" style="font-size: 50px;"></i> 
            </a>
        </button>
    </div>
</section>


{% endblock %}

flask_app/templates/litters.html
{% extends 'base.html' %}


{% block content %}

<!-- cuiburile E si D -->

<!-- poze cu parintii, poze cu copiii -->

<section class="litter-section">
    <div class="litter-header">
        <div class="parent-info">
            <div class="parent mother">
                <img src="{{ url_for('static', filename='images/fleur-de-lys.jpg') }}" alt="Fleur de Lys">
                <h3>Mama: Fleur de Lys</h3>
            </div>
            <div class="parent father">
                <img src="{{ url_for('static', filename='images/cronos.jpg') }}" alt="Cronos">
                <h3>Tatăl: Cronos</h3>
            </div>
        </div>
        <h2 class="litter-title">Cuibul E: Decembrie, 2025</h2>
    </div>

    <div class="kittens-gallery">
        <h3>Puii disponibili: </h3>
        <div class="kittens-grid">
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/ekko.jpg') }}" alt="Ekko">
                <p>Ekko</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/eros-nimbus.jpg') }}" alt="Eros-Nimbus">
                <p>Eros Nimbus</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/enzo-furrari.jpg') }}" alt="Enzo-Furrari">
                <p>Enzo Furrari</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/evita.jpg') }}" alt="Evita">
                <p>Evita</p>
            </div>
        </div>
    </div>
</section>

<section class="litter-section">
    <div class="litter-header">
        <div class="parent-info">
            <div class="parent mother">
                <img src="{{ url_for('static', filename='images/margot.jpg') }}" alt="Margot">
                <h3>Mama: Margot</h3>
            </div>
            <div class="parent father">
                <img src="{{ url_for('static', filename='images/armagedon.jpg') }}" alt="Armagedon">
                <h3>Tatăl: Armagedon</h3>
            </div>
        </div>
        <h2 class="litter-title">Cuibul D: August, 2024</h2>
    </div>

    <div class="kittens-gallery">
        <h3>Kittens Available</h3>
        <div class="kittens-grid">
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/dante.jpg') }}" alt="Dante">
                <p>Dante</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/dusty.jpg') }}" alt="Dusty">
                <p>Dusty</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/daphne.jpg') }}" alt="Daphne">
                <p>Daphne</p>
            </div>
            <div class="kitten-card">
                <img src="{{ url_for('static', filename='images/daemon.jpg') }}" alt="Daemon">
                <p>Daemon</p>
            </div>
        </div>
    </div>
</section>

<section id="litter-cta">
    <h2>Interesat de un pisoi din cuiburile noastre?</h2>
    <p>Contactează-ne pentru mai multe detalii sau pentru a rezerva un pisoi din cuiburile noastre disponibile!</p>
    <a href="/contact" class="litter-cta-button">Contactează-ne</a>
</section>

{% endblock %}

flask_app/templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
<section id="thank-you-section">
    <div class="thank-you-container">
        <h2>Mulțumim pentru mesajul tău!</h2>
        <p>Am primit mesajul tău și vom răspunde cât mai curând posibil. Îți mulțumim că ne-ai contactat!</p>
        <a href="/" class="thank-you-cta-button">Întoarce-te pe pagina principală</a>
    </div>
</section>
{% endblock %}